import Head from "next/head";
import React, { useEffect } from "react";
import { TodoItem } from "~/components/TodoItem";
import { useTodos } from "~/contexts/TodosContext";

export default function Home() {
  const { todos, newTodoInput, handleNewTodoChange, addNewTodo } = useTodos();

  useEffect(() => {
    document.body.className = "bg-charcoal-700";
  });

  const handleKeypress = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") {
      addNewTodo();
    }
  };

  return (
    <>
      <Head>
        <title>Endless Todos</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col">
        <div className="bg-charcoal-800 p-5 text-center">
          <h1 className="text-2xl font-bold tracking-wide text-white">
            Endless Todos
          </h1>
        </div>
        <main className="mx-auto max-w-md justify-center pt-32 text-white">
          <input
            type="text"
            placeholder="Add todo Item"
            className="border-b border-charcoal-600 bg-transparent bg-none py-2"
            onKeyDown={handleKeypress}
            value={newTodoInput}
            onChange={handleNewTodoChange}
          />

          <div className="mt-2">
            {todos.length >= 1 ? (
              <ul>
                {todos.map((todo) => (
                  <TodoItem key={todo.id} todo={todo} indentLevel={0} />
                ))}
              </ul>
            ) : (
              <p>No todos</p>
            )}
          </div>
        </main>
      </div>
    </>
  );
}
