import Head from "next/head";
import React, { useEffect } from "react";
import { TodosContext } from "~/contexts/TodosContext";

export interface Todo {
  text: string;
  completed: boolean;
  id: number;
  children?: Todo[];
}

interface TodosState {
  todos: Todo[],
  changeTodoText: (
    event: React.ChangeEvent<HTMLInputElement>,
    id: number
  ) => void,
  completeTodo: (id: number) => void
}



export default function Home() {
  

  useEffect(() => {
    document.body.className = "bg-charcoal-700";
  });

  return (
    <>
      <Head>
        <title>Endless Todos</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col">
        <div className="bg-charcoal-800 p-5 text-center">
          <h1 className="text-2xl font-bold tracking-wide text-white">
            Endless Todos
          </h1>
        </div>
          <TodosContext>
          <main className="mx-auto max-w-md justify-center pt-32 text-white">
          <input
            type="text"
            placeholder="Add todo Item"
            className="border-b border-charcoal-600 bg-transparent bg-none py-2"
            onKeyDown={handleKeypress}
            value={newTodoInput}
            onChange={handleNewTodoChange}
          />

          <ul className="mt-2">
            {todos.map((todo) => {
              if(todo.children?.length >= 1) {
                <TodoItem todos={todos} />
              }
              return (
                
              )
            })}
          </ul>
        </main>
          </TodosContext>
      </div>
    </>
  );
}
